databases:
  - name: qrcode_db
    databaseName: qrcode_db
    user: qrcode_db

services:
  - type: web
    name: qrcode
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qrcode_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false