databases:
  - name: qrcode
    databaseName: qrcode
    user: qrcode

services:
  - type: web
    name: qrcode
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qrcode
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true