databases:
  - name: qrcodes
    databaseName: qrcode
    user: qrcode

services:
  - type: web
    name: qrcode
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qrcode
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false